'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useAppDispatch, useAppSelector } from '@store/hooks';
import { Empty, PlayerCard, ConnectButton, CourtCard, GameCard } from '@shared/components/cards';
import { SportFilters } from '@shared/components/filters';
import { Icon } from '@shared/components/icon';
import { areas, courts } from '@shared/data/sportbuddy';
import { sports, type Player, type Sport, type Level } from '@shared/models/sportbuddy.model';
import { updateProfile, switchViewer } from '../store/sportbuddy.action';
import { profileProblem } from '@shared/services/demo.service';
export function CommunityPage() {
  const data = useAppSelector(s => s.sportbuddy.data); const [sport, setSport] = useState('All sports'); const [area, setArea] = useState('All areas'); const [query, setQuery] = useState(''); const [tab, setTab] = useState('Discover players');
  if (!data) return <div className="page-width inner-page" role="status">Finding your next teammates…</div>;
  const relevant = data.connections.filter(c => c.from === data.viewerId || c.to === data.viewerId);
  const requests = relevant.filter(c => c.status === 'pending' && c.to === data.viewerId);
  const players = data.players.filter(p => p.id !== data.viewerId && (sport === 'All sports' || p.sports.includes(sport as Sport)) && (area === 'All areas' || p.area === area) && p.name.toLowerCase().includes(query.toLowerCase()) && (tab === 'Discover players' || relevant.some(c => (c.from === p.id || c.to === p.id) && (tab === 'Connections' ? c.status === 'accepted' : c.status === 'pending'))));
  return <div className="page-width inner-page"><div className="page-heading"><p className="kicker">SAME SPORT. NEW FRIENDS.</p><h1>Find your <em>kind of people.</em></h1><p>A shared love of the game is a pretty good place to start.</p></div><div className="tabs">{['Discover players', 'Connections', 'Requests'].map(t => <button key={t} className={tab === t ? 'selected' : ''} aria-pressed={tab === t} onClick={() => setTab(t)}>{t}{t === 'Requests' && requests.length > 0 && <span className="count-badge">{requests.length}</span>}</button>)}</div><SportFilters selected={sport} onChange={setSport}/><div className="filter-toolbar"><label className="search-input"><Icon name="search" size={18}/><input aria-label="Search players" placeholder="Find a player" value={query} onChange={e => setQuery(e.target.value)}/></label><select aria-label="Player area" value={area} onChange={e => setArea(e.target.value)}><option>All areas</option>{areas.map(a => <option key={a.name}>{a.name}</option>)}</select></div><div className="results-heading"><span><b>{players.length} players</b> to share the court with</span><span className="muted">Example community</span></div><div className="player-grid">{players.map(p => <PlayerCard key={p.id} player={p}/>)}{!players.length && <Empty title={tab === 'Connections' ? 'Your crew starts here.' : 'No players to show.'}>Explore players or change your filters.</Empty>}</div><div className="community-note"><Icon name="users"/><p>Try connecting with another demo player, then switch players in <Link href="/profile">Your profile</Link> to accept the request. No real people are contacted.</p></div></div>;
}
export function PlayerPage({ id }: { id: string }) {
  const data = useAppSelector(s => s.sportbuddy.data); if (!data) return <div className="page-width inner-page" role="status">Loading profile…</div>;
  const player = data.players.find(p => p.id === id); if (!player) return <div className="page-width inner-page"><Empty title="Player not found."><Link href="/community">Meet the community</Link></Empty></div>;
  const games = data.games.filter(g => g.hostId === id && g.status === 'open' && Date.parse(g.start) > Date.now());
  return <div className="page-width inner-page"><Link href="/community" className="back-link">← Community</Link><section className="public-profile"><span className="avatar jumbo" style={{ background: player.color }}>{player.initials}</span><div><p className="kicker">YOUR NEXT SPORTS BUDDY</p><h1>{player.name}</h1><p className="icon-line"><Icon name="pin" size={17}/>{player.area} · {player.level}</p><p className="body-copy">{player.bio}</p><div className="chips">{player.sports.map(s => <span className="tag" key={s}>{s}</span>)}</div></div><ConnectButton player={player}/></section><section className="section"><div className="section-heading"><h2>Games hosted by {player.name.split(' ')[0]}</h2></div><div className="game-grid">{games.map(g => <GameCard key={g.id} game={g}/>)}{!games.length && <Empty title="No upcoming hosted games."/>}</div></section></div>;
}
export function ProfilePage() {
  const data = useAppSelector(s => s.sportbuddy.data); const dispatch = useAppDispatch();
  if (!data) return <div className="page-width inner-page" role="status">Loading your profile…</div>;
  const player = data.players.find(p => p.id === data.viewerId)!; const saved = courts.filter(c => data.saved[data.viewerId]?.includes(c.id));
  const connectionCount = data.connections.filter(c => c.status === 'accepted' && (c.from === player.id || c.to === player.id)).length;
  return <div className="page-width inner-page"><div className="page-heading"><p className="kicker">MAKE YOURSELF AT HOME</p><h1>Hey, {player.name.split(' ')[0]}<em>.</em></h1><p>Your sports, your people, your next chapter.</p></div><div className="profile-summary"><span className="avatar large" style={{ background: player.color }}>{player.initials}</span><div><h3>{player.name}</h3><span>{player.area}</span></div><Link href="/my-games"><b>{data.games.filter(g => g.playerIds.includes(player.id) && g.status === 'open' && Date.parse(g.start) > Date.now()).length}</b> Upcoming games</Link><Link href="/community"><b>{connectionCount}</b> Connections</Link><span><b>{saved.length}</b> Saved courts</span></div><div className="host-layout"><ProfileForm key={player.id} player={player}/><aside className="host-tips"><p className="kicker">EXPLORE THE DEMO</p><h2>Try the other side<br/>of the invite.</h2><p>Switch to another sample player to accept a connection request or join a game you hosted.</p><label className="stacked-label">Demo player<select aria-label="Demo player" value={data.viewerId} onChange={e => dispatch(switchViewer(e.target.value))}>{data.players.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p className="fine-print">This is a demo identity switch, not account authentication. Changes are saved only in this browser.</p><Link href="/my-games" className="button outline">My games <Icon name="arrow" size={17}/></Link></aside></div><section className="section"><div className="section-heading"><h2>Your saved spots.</h2><Link href="/courts" className="text-link">Find more courts →</Link></div><div className="court-grid">{saved.map(c => <CourtCard key={c.id} court={c}/>)}{!saved.length && <Empty title="Keep your favourites close.">Tap the heart on a court to save it here.</Empty>}</div></section></div>;
}
function ProfileForm({ player }: { player: Player }) {
  const dispatch = useAppDispatch(); const [selected, setSelected] = useState<Sport[]>(player.sports); const [error, setError] = useState('');
  return <form className="form-panel" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const name = String(f.get('name')).trim(); const updated = { ...player, name, initials: name.split(/\s+/).slice(0, 2).map(n => n[0]).join('').toUpperCase(), bio: String(f.get('bio')).trim(), area: String(f.get('area')), level: String(f.get('level')) as Level, sports: selected }; const problem = profileProblem(updated); if (problem) { setError(problem); return; } setError(''); dispatch(updateProfile(updated)); }}><h2>A little about you</h2><label>Display name<input name="name" required maxLength={60} defaultValue={player.name}/></label><div className="form-row"><label>Your area<select name="area" defaultValue={player.area}>{areas.map(a => <option key={a.name}>{a.name}</option>)}</select></label><label>Skill level<select name="level" defaultValue={player.level}>{['All levels', 'Beginner', 'Intermediate', 'Advanced'].map(l => <option key={l}>{l}</option>)}</select></label></div><fieldset><legend>Your sports</legend><div className="checkbox-chips">{sports.map(s => <label key={s}><input type="checkbox" checked={selected.includes(s)} onChange={() => setSelected(selected.includes(s) ? selected.filter(v => v !== s) : [...selected, s])}/>{s}</label>)}</div></fieldset><label>Bio<textarea name="bio" rows={4} maxLength={300} defaultValue={player.bio}/><small>Tell future teammates a little about yourself. Up to 300 characters.</small></label>{error && <p className="field-error" role="alert">{error}</p>}<button type="submit" className="button dark">Save profile <Icon name="check" size={18}/></button></form>;
}
