'use client';
import { useState } from 'react';
import Link from 'next/link';
import { courts } from '@shared/data/sportbuddy';
import { CourtCard, Empty, GameCard } from '@shared/components/cards';
import { SportFilters, useLocation, LocationControls, ViewToggle } from '@shared/components/filters';
import { VenueMap } from '@shared/components/venue-map';
import { distanceKm, mapsUrl } from '@core/location/location';
import { Icon } from '@shared/components/icon';
import { CourtArt } from '@shared/components/court-art';
import { useAppDispatch, useAppSelector } from '@store/hooks';
import { toggleSave } from '../store/sportbuddy.action';
export function CourtsPage() {
  const [sport, setSport] = useState('All sports'); const [query, setQuery] = useState(''); const [facility, setFacility] = useState('Any setting'); const [radius, setRadius] = useState(25); const [map, setMap] = useState(false); const location = useLocation();
  const filtered = courts.filter(c => (sport === 'All sports' || c.sport === sport) && `${c.name} ${c.area}`.toLowerCase().includes(query.toLowerCase()) && (facility === 'Any setting' || c.indoor === (facility === 'Indoor')) && distanceKm(location.center, c) <= radius).sort((a, b) => distanceKm(location.center, a) - distanceKm(location.center, b));
  return <div className="page-width inner-page"><div className="page-heading"><p className="kicker">YOUR NEXT FAVOURITE SPOT</p><h1>Find a court. <em>Make it yours.</em></h1><p>Good spaces for great games, right in your neighbourhood.</p></div><SportFilters selected={sport} onChange={setSport}/><div className="filter-toolbar"><label className="search-input"><Icon name="search" size={18}/><input aria-label="Search courts" placeholder="Search courts or areas" value={query} onChange={e => setQuery(e.target.value)}/></label><LocationControls location={location}/><select aria-label="Court setting" value={facility} onChange={e => setFacility(e.target.value)}>{['Any setting', 'Indoor', 'Outdoor'].map(v => <option key={v}>{v}</option>)}</select><select aria-label="Search radius" value={radius} onChange={e => setRadius(Number(e.target.value))}>{[5, 10, 25, 50, 100].map(r => <option key={r} value={r}>Within {r} km</option>)}</select></div><div className="results-heading"><span><b>{filtered.length} courts</b> around {location.area}</span><ViewToggle map={map} setMap={setMap}/></div><div className={map ? 'map-results' : ''}><div className="court-grid">{filtered.map(c => <CourtCard key={c.id} court={c} distance={distanceKm(location.center, c)}/>)}{!filtered.length && <Empty/>}</div>{map && <VenueMap venues={filtered} center={location.center} onSearch={location.searchArea}/>}</div><p className="distance-note">Distances are approximate straight-line distances. All courts and prices are demo examples.</p></div>;
}
export function CourtDetailPage({ id }: { id: string }) {
  const court = courts.find(c => c.id === id); const data = useAppSelector(s => s.sportbuddy.data); const dispatch = useAppDispatch();
  if (!court) return <div className="page-width inner-page"><Empty title="Court not found."><Link href="/courts">Browse all courts</Link></Empty></div>;
  const saved = !!data?.saved[data.viewerId]?.includes(id);
  const games = data?.games.filter(g => g.courtId === id && g.status === 'open' && Date.parse(g.start) > Date.now()) ?? [];
  return <div className="page-width inner-page"><Link className="back-link" href="/courts">← All courts</Link><div className="detail-art"><CourtArt sport={court.sport}/><span className="tag">Sample venue</span></div><div className="detail-layout"><section><p className="kicker">{court.sport} · {court.indoor ? 'INDOOR' : 'OUTDOOR'}</p><h1>{court.name}</h1><p className="icon-line"><Icon name="pin"/>{court.address}</p><h2>A little space to play.</h2><p className="body-copy">Your next friendly match starts here. Explore the facilities, bring your crew, or join a game with someone new. This is an example venue for exploring SportBuddy.</p><h3>Make yourself at home</h3><div className="facility-grid">{court.facilities.map(f => <span key={f}><Icon name="check" size={17}/>{f}</span>)}</div><h3>Find your way</h3><VenueMap venues={[court]} center={court}/></section><aside className="detail-aside"><p className="kicker">THE COURT AT A GLANCE</p><h2>{court.price ? <>RM {court.price}<small> / hour</small></> : 'Free to play'}</h2><p>Indicative demo price</p><hr/><p className="icon-line"><Icon name="clock"/>{court.hours}</p><p className="icon-line"><Icon name="users"/>{games.length} upcoming games</p><a href={mapsUrl(court, true)} target="_blank" rel="noreferrer" className="button dark">Get directions <Icon name="arrow" size={17}/></a><a href={mapsUrl(court)} target="_blank" rel="noreferrer" className="button outline">Open in Google Maps</a><button className="button outline" aria-pressed={saved} onClick={() => dispatch(toggleSave(id))}><Icon name="heart" size={17}/>{saved ? 'Saved court' : 'Save this court'}</button><Link className="text-link" href={`/games/new?court=${id}`}>Host a game here <Icon name="plus" size={17}/></Link><p className="fine-print">Court bookings are arranged separately with the venue. Example map coordinates are for demo use.</p></aside></div><section className="section"><div className="section-heading"><h2>Meet you on this court.</h2></div><div className="game-grid">{games.map(g => <GameCard key={g.id} game={g}/>)}{!games.length && <Empty title="Start something good."><Link href={`/games/new?court=${id}`}>Host the first game at this court.</Link></Empty>}</div></section></div>;
}
